version: '3.8'

services:
  app:
    build:Semana1/Actividad1/devops-practice
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    container_name: devops-practice-container
