services:
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: trivia_db
    ports:
      - "5432:5432"
  
  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/trivia_db
    depends_on:
      - db
  
  init_db:
    build: .
    command: sh -c "PYTHONPATH=/app/src ./src/wait-for-db.sh python -m src.init_db"
    depends_on:
      - db
    volumes:
      - .:/app


      