name: Python CI
on:
  push:
    branches:
      - tarea1/feature-db
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Set JAVA_HOME for Java 17
        run: echo "JAVA_HOME_17_X64=$(java -XshowSettings:properties -version 2>&1 | grep 'java.home' | awk '{print $3}')" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: Semana3/Tarea1-CC3S2/trivia-game-python

      - name: Install Sonar Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          mv sonar-scanner-4.6.2.2472-linux sonar-scanner
          echo "PATH=$PATH:${{ github.workspace }}/sonar-scanner/bin" >> $GITHUB_ENV
          echo "JAVA_HOME=${{ github.workspace }}/sonar-scanner/bin" >> $GITHUB_ENV
      
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=danicade24_Actividades-CC3S2 \
            -Dsonar.organization=danicade24 \
            -Dsonar.sources=Semana3/Tarea1-CC3S2/trivia-game-python \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/Semana3/Tarea1-CC3S2/trivia-game-python" >> $GITHUB_ENV

      - name: Run tests
        run: pytest
        working-directory: Semana3/Tarea1-CC3S2/trivia-game-python
