name: Python CI
on:
  push:
    branches:
      - tarea1/feature-db
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: Semana3/Tarea1-CC3S2/trivia-game-python

      - name: Run tests
        run: PYTHONPATH=Semana3/Tarea1-CC3S2/trivia-game-python pytest
        working-directory: Semana3/Tarea1-CC3S2/trivia-game-python
